version: '3'
services:
  installer:
    build: Docker/installer
    restart: on-failure
    volumes:
      - ./:/var/www
    env_file:
      - ./.env.docker
    links:
      - db
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file: ./.env.docker
    expose:
      - 3306
    volumes:
      - ./Docker/database:/var/lib/mysql

  php-fpm:
    build: ./Docker/php-fpm
    env_file:
      - ./.env.docker
    expose:
      - 9000
    volumes:
      - ./:/var/www
      - ./Docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    links:
      - db
    depends_on:
      - installer
      - db
    tty: true
    restart: always


  nginx:
    image: nginx
    volumes:
      - ./:/var/www
      - ./Docker/log/nginx:/var/log/nginx
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    ports:
      - 8123:80